/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hudson_donglingmusic_bitmapblurjni_BitmapBlur */

#ifndef _Included_com_hudson_donglingmusic_bitmapblurjni_BitmapBlur
#define _Included_com_hudson_donglingmusic_bitmapblurjni_BitmapBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hudson_donglingmusic_bitmapblurjni_BitmapBlur
 * Method:    blurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_hudson_donglingmusic_bitmapblurjni_BitmapBlur_blurBitmap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
